name: navigation_utils
description: The missing navigation library for Navigator 2.
version: 0.1.0
homepage: https://codelessly.com
repository: https://github.com/rayliverified/NavigationUtils
false_secrets:
  - /example_auth/android/app/google-services.json
  - /example_auth/ios/Runner/GoogleService-Info.plist
  - /example_auth/example_auth/lib/firebase_options.dart
  - /example_auth/macos/Runner/GoogleService-Info.plist
  - /example_auth/lib/firebase_options.dart

environment:
  sdk: ">=2.17.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
